# 3. 연산

## 3-1. 산술 연산

### 1차원 배열

In [1]:
import numpy as np

In [11]:
a = np.arange(1, 5)  # 1 ~ 4
b = np.arange(5, 9)  # 5 ~ 8

In [12]:
a, b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [13]:
# 덧셈 (shape이 같아야 함)
a + b

array([ 6,  8, 10, 12])

In [14]:
# 뺄셈
a - b

array([-4, -4, -4, -4])

In [15]:
# 곱셈
a * b

array([ 5, 12, 21, 32])

In [16]:
# 나눗셈
a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

### 2차원 배열

In [17]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
b = np.arange(7, 13).reshape(2, 3)
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [21]:
# 덧셈 (shape이 같아야 함)
a + b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [22]:
# 뺄셈
a - b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [24]:
# 단순 곱셈 (이렇게는 안 쓰임)
a * b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [25]:
# 나눗셈
a / b

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

### 행렬의 곱셈(dot product)

In [27]:
# 행렬의 곱셈 (중요!)
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
b = np.arange(1, 7).reshape(3, 2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
# 행렬의 곱셈 (중요!)
np.dot(a, b)

array([[22, 28],
       [49, 64]])

In [30]:
a.dot(b)

array([[22, 28],
       [49, 64]])

In [35]:
# 비교 (Element-wise comparison)
a <= 2

array([[ True,  True, False],
       [False, False, False]])

### 숫자(Scalar)와의 연산 (Broadcasting)

In [36]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [37]:
a + 3

array([4, 5, 6])

In [38]:
a - 3

array([-2, -1,  0])

In [39]:
a * 3

array([3, 6, 9])

In [40]:
a / 3

array([0.33333333, 0.66666667, 1.        ])

## 3-2. Aggregation 함수

### 1차원 배열

In [96]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [97]:
# max값 찾기
np.max(a)

5

In [98]:
a.max()

5

In [99]:
# min값 찾기
np.min(a), a.min()

(1, 1)

In [100]:
# sum() : 배열 요소의 합 구하기
np.sum(a)

15

In [101]:
# mean() : 평균
np.mean(a)

3.0

In [107]:
# 위 데이터를 하나의 값으로 표현하려면? 평균을 이용
a = np.array([1, 2, 3, 4, 100])   # 이상치(outlier)가 있는 경우 평균보다는 중앙값을 이용하는 것이 좋음

# median() : 중앙값 (중앙에 위치한 값, 중위값)
np.median(a)

3.0

In [110]:
# 데이터가 짝수개인 경우 (중간에 위치한 두 개의 숫자의 평균으로 중앙값을 계산)
a = np.array([1, 2, 3, 100])
np.median(a)

2.5

In [112]:
# std() : 표준편차 (standard deviation), 위키백과
np.std(a)

42.44113570582201

### 2차원 배열

In [3]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
np.max(a)

6

In [117]:
# 2차원 배열의 경우 axis를 주어 각 행과 열의 max값을 구할 수 있음
np.max(a, axis=0)

array([4, 5, 6])

In [118]:
np.max(a, axis=1)

array([3, 6])

In [121]:
np.min(a)

1

In [123]:
np.min(a, axis=0), np.min(a, axis=1)

(array([1, 2, 3]), array([1, 4]))

In [124]:
np.sum(a)

21

In [125]:
np.sum(a, axis=0)

array([5, 7, 9])

In [126]:
np.sum(a, axis=1)

array([ 6, 15])

In [127]:
# cumsum, corrcoef : 검색으로 찾아보기

In [6]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [7]:
np.cumsum(a, axis=0)

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [8]:
np.cumsum(a, axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [45]:
# 피어슨 상관계수 (-1과 1사이 값)
# 두 변수 사이의 연관성을 나타내는 수치
# 키와 몸무게의 상관관계
h = [160, 165, 170, 180]
w = [47, 55, 70, 85]
np.corrcoef(h, w)  # shape이 같아야 함

array([[1.        , 0.99040485],
       [0.99040485, 1.        ]])

In [46]:
ha = np.mean(h)
wa = np.mean(w)
ha, wa

(168.75, 64.25)

In [47]:
a = np.sqrt(np.sum((h - ha)**2))
a

14.79019945774904

In [48]:
b = np.sqrt(np.sum((w - wa) ** 2))
b

29.098969053902923

In [49]:
c = np.sum((h - ah) * (w - aw))
c

426.25

In [50]:
r = c / (a * b)
r

0.990404850180661