# 4. 정렬

## 4-1. 1차원 정렬

In [1]:
import numpy as np

In [63]:
np.random.seed(123)
arr = np.random.randint(1, 10, size=10)  # 1~9
arr

array([3, 3, 7, 2, 4, 7, 2, 1, 2, 1])

In [64]:
# 오름차순 정렬
np.sort(arr)

array([1, 1, 2, 2, 2, 3, 3, 4, 7, 7])

In [65]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([7, 7, 4, 3, 3, 2, 2, 2, 1, 1])

In [66]:
# np.sort()를 하면 arr 원본배열을 정렬하지는 않음
arr

array([3, 3, 7, 2, 4, 7, 2, 1, 2, 1])

In [67]:
sort_arr = np.sort(arr)
sort_arr

array([1, 1, 2, 2, 2, 3, 3, 4, 7, 7])

In [68]:
# 배열.sort()를 하면 값이 저장됨 (in-place 메소드)
arr.sort()

In [69]:
arr

array([1, 1, 2, 2, 2, 3, 3, 4, 7, 7])

## 4-2. 2차원 정렬

In [2]:
np.random.seed(123)
arr2 = np.random.randint(1, 10, size=(3, 4))
arr2

array([[3, 3, 7, 2],
       [4, 7, 2, 1],
       [2, 1, 1, 4]])

In [55]:
np.sort(arr2) # axis=1과 동일

array([[2, 3, 3, 7],
       [1, 2, 4, 7],
       [1, 1, 2, 4]])

In [56]:
# 열 정렬
np.sort(arr2, axis=0)

array([[2, 1, 1, 1],
       [3, 3, 2, 2],
       [4, 7, 7, 4]])

In [57]:
# 행 정렬
np.sort(arr2, axis=1)

array([[2, 3, 3, 7],
       [1, 2, 4, 7],
       [1, 1, 2, 4]])

In [58]:
arr2

array([[3, 3, 7, 2],
       [4, 7, 2, 1],
       [2, 1, 1, 4]])

In [4]:
# index를 반환하는 argsort
np.argsort(arr2)  # axis=1과 동일

array([[3, 0, 1, 2],
       [3, 2, 0, 1],
       [1, 2, 0, 3]], dtype=int64)

In [5]:
np.argsort(arr2, axis=0)

array([[2, 2, 2, 1],
       [0, 0, 1, 0],
       [1, 1, 0, 2]], dtype=int64)