# 5. 인덱싱과 슬라이싱

## 5-1. 인덱싱

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[0]

0

In [4]:
arr[-1]

9

In [5]:
arr2 = np.arange(12).reshape(3, 4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
# 파이썬 2차원 배열 인덱싱 방법
arr2[0][2]

2

In [7]:
# numpy에서는 다차원 indexing을 지원함 (이 방식 권장)
arr2[0, 2]

2

In [10]:
arr2[-1, -2]

10

## 5-2. 슬라이싱

### 1차원 배열

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# 2~끝까지 슬라이싱
arr[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# 처음~4까지 슬라이싱
arr[:5]

array([0, 1, 2, 3, 4])

In [15]:
# 2~4까지 슬라이싱
arr[2:5]

array([2, 3, 4])

In [16]:
# 0~8까지 슬라이싱
print(arr[:9])
arr[:-1]

[0 1 2 3 4 5 6 7 8]


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
# 전체
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# 슬라이싱을 한 후 값을 변경하면 원본에도 영향을 줄까?
new_arr = arr[2:5]
new_arr

array([2, 3, 4])

In [19]:
new_arr[0] = 100
new_arr

array([100,   3,   4])

In [20]:
arr

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

In [21]:
# 원본에 영향을 주지 않으려면? 복사본을 만들자!
new_arr = arr[2:5].copy()
new_arr

array([100,   3,   4])

In [22]:
new_arr[0] = 200
new_arr

array([200,   3,   4])

In [23]:
arr

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

### 2차원 배열

In [2]:
arr2 = np.arange(1, 13).reshape(3, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
# 첫번째 행을 모두 가져오려는 경우
arr2[0, :]

array([1, 2, 3, 4])

In [9]:
# 세번째 열을 모두 가져오려는 경우
arr2[:, 2]

array([ 3,  7, 11])

In [10]:
# 첫번째, 두번째 행 모두 가져올 경우
arr2[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
# 두번째, 세번째 열 모두 가져올 경우
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [12]:
# [[2, 3]
# [6, 7]]을 가져올 경우
arr2[:2, 1:-1]

array([[2, 3],
       [6, 7]])

## 5-3. Fancy 인덱싱

추출하고 싶은 인덱스 배열로 인덱싱하기

In [13]:
# 1차원 배열
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# [1, 3, 5] 1차원 배열 만들기
np.array([arr[0], arr[2], arr[4]])

array([1, 3, 5])

In [23]:
# 슬라이싱
arr[0:6:2]

array([1, 3, 5])

In [18]:
# 인덱스로 배열 만들기
arr[[0, 2, 4]]  # arr[1, 2, 4] 이렇게 하면 안됨

array([1, 3, 5])

In [19]:
# 2차원 배열
arr2 = np.arange(1, 13).reshape(3, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
# [[1, 2, 3, 4],
#  [5, 6, 7, 8]] 2차원 배열 만들기
np.array([arr2[0], arr2[1]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
# 슬라이싱
arr2[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
# Fancy 인덱싱
arr2[[0, 1]]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
# 주의
arr2[0, 1]

2

In [30]:
# [[2, 3],
#  [6, 7],
#  [10, 11]] 2차원 배열 만들기
# 슬라이싱
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [31]:
# Fancy 인덱싱
arr2[:, [1, 2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

## 5-4. Boolean 인덱싱

Boolean 값을 이용하여 인덱싱하기

In [53]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [54]:
cond = [True, False, True, False, True]

In [55]:
arr[cond]

array([0, 2, 4])

In [43]:
# Boolean 인덱싱 시 갯수 주의하기
cond = [True, False, True]
arr[cond]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 3

In [57]:
# 조건 필터링을 통해 인덱싱하기
arr > 2

array([False, False, False,  True,  True])

In [58]:
# arr[조건필터]
arr[arr > 2]

array([3, 4])

In [59]:
# 짝수 뽑기
arr % 2 == 0

array([ True, False,  True, False,  True])

In [60]:
arr[arr % 2 == 0]

array([0, 2, 4])

In [65]:
# &, | operator 사용 가능 (괄호 주의)
#(arr >= 1) & (arr <= 3)
arr[(arr >= 1) & (arr <= 3)]

array([1, 2, 3])

In [66]:
arr[(arr < 1) | (arr > 3)]

array([0, 4])